package br.edu.qi.model;
// Generated Nov 25, 2017 5:45:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name="modelo"
    ,catalog="dconcessionaria"
)
public class Modelo  implements java.io.Serializable {


     private Integer idModelo;
     private Marca marca;
     private String nomeModelo;
     private Set<Carro> carros = new HashSet<Carro>(0);

    public Modelo() {
    }

    public Modelo(Marca marca, String nomeModelo, Set<Carro> carros) {
       this.marca = marca;
       this.nomeModelo = nomeModelo;
       this.carros = carros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_modelo", unique=true, nullable=false)
    public Integer getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_marca")
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    
    @Column(name="nome_modelo", length=50)
    public String getNomeModelo() {
        return this.nomeModelo;
    }
    
    public void setNomeModelo(String nomeModelo) {
        this.nomeModelo = nomeModelo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modelo")
    public Set<Carro> getCarros() {
        return this.carros;
    }
    
    public void setCarros(Set<Carro> carros) {
        this.carros = carros;
    }

    @Override
    public String toString() {
        if(this.marca!= null)
            return this.marca+" "+this.nomeModelo;
        return this.nomeModelo;
    }

    



}


