package br.edu.qi.model;
// Generated Nov 15, 2017 9:43:23 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CarroAcessorio generated by hbm2java
 */
@Entity
@Table(name="carro_acessorio"
    ,catalog="dbrevenda"
)
public class CarroAcessorio  implements java.io.Serializable {


     private CarroAcessorioId id;
     private Acessorio acessorio;
     private Carro carro;

    public CarroAcessorio() {
    }

	
    public CarroAcessorio(CarroAcessorioId id) {
        this.id = id;
    }
    public CarroAcessorio(CarroAcessorioId id, Acessorio acessorio, Carro carro) {
       this.id = id;
       this.acessorio = acessorio;
       this.carro = carro;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idAcessorio", column=@Column(name="id_acessorio") ), 
        @AttributeOverride(name="idCarro", column=@Column(name="id_carro") ) } )
    public CarroAcessorioId getId() {
        return this.id;
    }
    
    public void setId(CarroAcessorioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_acessorio", insertable=false, updatable=false)
    public Acessorio getAcessorio() {
        return this.acessorio;
    }
    
    public void setAcessorio(Acessorio acessorio) {
        this.acessorio = acessorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_carro", insertable=false, updatable=false)
    public Carro getCarro() {
        return this.carro;
    }
    
    public void setCarro(Carro carro) {
        this.carro = carro;
    }




}


