package br.edu.qi.model;
// Generated Nov 15, 2017 12:39:38 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CarroAcessorio generated by hbm2java
 */
@Entity
@Table(name="carro_acessorio"
    ,catalog="dbrevenda"
)
public class CarroAcessorio  implements java.io.Serializable {


     private Integer idCarroAcessorio;
     private Acessorio acessorio;
     private Carro carro;

    public CarroAcessorio() {
    }

    public CarroAcessorio(Acessorio acessorio, Carro carro) {
       this.acessorio = acessorio;
       this.carro = carro;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_carro_acessorio", unique=true, nullable=false)
    public Integer getIdCarroAcessorio() {
        return this.idCarroAcessorio;
    }
    
    public void setIdCarroAcessorio(Integer idCarroAcessorio) {
        this.idCarroAcessorio = idCarroAcessorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_acessorio")
    public Acessorio getAcessorio() {
        return this.acessorio;
    }
    
    public void setAcessorio(Acessorio acessorio) {
        this.acessorio = acessorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_carro")
    public Carro getCarro() {
        return this.carro;
    }
    
    public void setCarro(Carro carro) {
        this.carro = carro;
    }




}


