package br.edu.qi.model;
// Generated Nov 15, 2017 9:43:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarroAcessorioId generated by hbm2java
 */
@Embeddable
public class CarroAcessorioId  implements java.io.Serializable {


     private Integer idAcessorio;
     private Integer idCarro;

    public CarroAcessorioId() {
    }

    public CarroAcessorioId(Integer idAcessorio, Integer idCarro) {
       this.idAcessorio = idAcessorio;
       this.idCarro = idCarro;
    }
   


    @Column(name="id_acessorio")
    public Integer getIdAcessorio() {
        return this.idAcessorio;
    }
    
    public void setIdAcessorio(Integer idAcessorio) {
        this.idAcessorio = idAcessorio;
    }


    @Column(name="id_carro")
    public Integer getIdCarro() {
        return this.idCarro;
    }
    
    public void setIdCarro(Integer idCarro) {
        this.idCarro = idCarro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarroAcessorioId) ) return false;
		 CarroAcessorioId castOther = ( CarroAcessorioId ) other; 
         
		 return ( (this.getIdAcessorio()==castOther.getIdAcessorio()) || ( this.getIdAcessorio()!=null && castOther.getIdAcessorio()!=null && this.getIdAcessorio().equals(castOther.getIdAcessorio()) ) )
 && ( (this.getIdCarro()==castOther.getIdCarro()) || ( this.getIdCarro()!=null && castOther.getIdCarro()!=null && this.getIdCarro().equals(castOther.getIdCarro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAcessorio() == null ? 0 : this.getIdAcessorio().hashCode() );
         result = 37 * result + ( getIdCarro() == null ? 0 : this.getIdCarro().hashCode() );
         return result;
   }   


}


